-- ============================================================================
-- Migration V001: Create Tenants Table (Public Schema)
-- ============================================================================
-- Purpose: Creates the tenants metadata table in the public schema
--
-- This table stores information about all tenants in the system.
-- Each tenant gets its own isolated schema: tenant_{uuid}
--
-- IMPORTANT: This table lives in the PUBLIC schema and is shared across
-- all tenants. It contains only metadata, not business data.
-- ============================================================================

-- Create tenants table in public schema
CREATE TABLE IF NOT EXISTS public.tenants (
    -- Primary key: UUID v4 generated by application
    id UUID PRIMARY KEY,

    -- Tenant business name (required)
    nome VARCHAR(255) NOT NULL,

    -- Schema name for this tenant (unique, required)
    -- Format: tenant_{uuid_without_hyphens}
    -- Example: tenant_a1b2c3d4e5f67890abcdef1234567890
    schema_name VARCHAR(255) UNIQUE NOT NULL,

    -- Tenant contact email (required)
    email VARCHAR(255) NOT NULL,

    -- Whether tenant is active (default: true)
    -- Inactive tenants cannot access the system
    ativo BOOLEAN DEFAULT true NOT NULL,

    -- Timestamp when tenant was created
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- Timestamp when tenant was last updated
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ============================================================================
-- Indexes
-- ============================================================================

-- Index for fast schema lookup (used by TenantRoutingDataSource)
CREATE INDEX IF NOT EXISTS idx_tenants_schema_name
ON public.tenants(schema_name);

-- Index for filtering active tenants
CREATE INDEX IF NOT EXISTS idx_tenants_ativo
ON public.tenants(ativo)
WHERE ativo = true;

-- Index for email lookup (used for tenant user management)
CREATE INDEX IF NOT EXISTS idx_tenants_email
ON public.tenants(email);

-- ============================================================================
-- Comments (PostgreSQL Documentation)
-- ============================================================================

COMMENT ON TABLE public.tenants IS
'Metadata table for all tenants in the multi-tenant system. Each tenant has an isolated schema.';

COMMENT ON COLUMN public.tenants.id IS
'Tenant UUID (primary key)';

COMMENT ON COLUMN public.tenants.nome IS
'Tenant business/company name';

COMMENT ON COLUMN public.tenants.schema_name IS
'PostgreSQL schema name for this tenant (format: tenant_{uuid_without_hyphens})';

COMMENT ON COLUMN public.tenants.email IS
'Tenant contact email address';

COMMENT ON COLUMN public.tenants.ativo IS
'Whether tenant is active and can access the system';

COMMENT ON COLUMN public.tenants.data_criacao IS
'Timestamp when tenant was created';

COMMENT ON COLUMN public.tenants.data_atualizacao IS
'Timestamp when tenant metadata was last updated';
